apiVersion: batch/v1
kind: Job
metadata:
  name: rebuild-search-index
spec:
  template:
    spec:
      containers:
      - name: gunicorn
        image: cpdbdev/backend:{{BACKEND_IMAGE_TAG}}
        command: ["cpdb/manage.py",  "rebuild_search_index"]
        env:
        - name: DB_NAME
          value: "{{POSTGRES_APP_DB}}"
        - name: DB_USER
          value: "{{POSTGRES_APP_USER}}"
        - name: DB_PASSWORD
          value: "{{POSTGRES_APP_PASSWORD}}"
        - name: DB_HOST
          value: pg-proxy
        - name: DJANGO_SETTINGS_MODULE
          value: "{{DJANGO_SETTINGS_MODULE}}"
      restartPolicy: Never
  backoffLimit: 4
