apiVersion: batch/v1
kind: Job
metadata:
  name: update-documents
spec:
  template:
    spec:
      containers:
      - name: gunicorn
        image: cpdbdev/backend:${BACKEND_IMAGE_TAG}
        command: ["cpdb/manage.py",  "update_documents"]
        env:
        - name: DB_NAME
          value: "${POSTGRES_APP_DB}"
        - name: DB_USER
          value: "${POSTGRES_APP_USER}"
        - name: DB_PASSWORD
          value: "${POSTGRES_APP_PASSWORD}"
        - name: DB_HOST
          value: pg-proxy
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            secretKeyRef:
              name: django
              key: setting-module
        - name: DOCUMENTCLOUD_USER
          valueFrom:
            secretKeyRef:
              name: documentcloud
              key: user
        - name: DOCUMENTCLOUD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: documentcloud
              key: password
      restartPolicy: Never
  backoffLimit: 4
