apiVersion: batch/v1
kind: Job
metadata:
  name: upload-document-requests
spec:
  template:
    spec:
      containers:
      - name: gunicorn
        image: cpdbdev/backend:{{BACKEND_IMAGE_TAG}}
        command: ["cpdb/manage.py",  "upload_document_requests"]
        env:
        - name: DB_NAME
          value: "{{POSTGRES_APP_DB}}"
        - name: DB_USER
          value: "{{POSTGRES_APP_USER}}"
        - name: DB_PASSWORD
          value: "{{POSTGRES_APP_PASSWORD}}"
        - name: DB_HOST
          value: pg-proxy
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            secretKeyRef:
              name: django
              key: setting-module
        - name: AIRTABLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: airtable
              key: api-key
        - name: AIRTABLE_PROJECT_KEY
          valueFrom:
            secretKeyRef:
              name: airtable
              key: project-key
      restartPolicy: Never
  backoffLimit: 4
