version: '3'
services:
  web:
    build: .
    environment:
      GUNICORN_RELOAD: "True"
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - .:/usr/src/app
    command: cpdb/manage.py runserver 0.0.0.0:80
  postgres:
    build: ./docker/postgres
    command: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:5-alpine
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  cpdpbot:
    build: ./docker/cpdpbot
    env_file: local.env

volumes:
  pgdata:
  esdata:
