---
  - name: Ensure psycopg2 module installed
    apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
    with_items:
      - python-psycopg2
      - postgresql-9.4-postgis-2.2
      - postgresql-server-dev-9.4
    tags: packages

  - name: setup postgresql.conf file
    copy: src=postgresql.conf dest=/etc/postgresql/9.4/main/postgresql.conf owner=postgres group=postgres mode=0640

  - name: setup pg_hba file
    template:
      src: pg_hba.conf.j2
      dest: /etc/postgresql/9.4/main/pg_hba.conf
      owner: postgres
      group: postgres
      mode: 0640

  - name: reload postgres
    service: name=postgresql state=reloaded enabled=yes

  - name: Ensure the database exist
    postgresql_db: name={{ application_name }}
    become: true
    become_user: postgres

  - name: Ensure user has access to database
    postgresql_user:
      db={{ db_name }} name={{ db_user }} password={{ db_password }}
      priv=ALL role_attr_flags=SUPERUSER
    become: true
    become_user: postgres

  - name: Ensure numeracy has access to cpdb database on data tables
    postgresql_user:
      db={{ db_name }} name=numeracy password={{ numeracy_db_password }}
      priv={{numeracy_postgres_priv}}
    become: true
    become_user: postgres
