---

- name: java | Update repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
    state: present
    filename: webupd8team-java

- name: java | Create source list file
  file:
    path: /etc/apt/sources.list.d/webupd8team-java.list
    state: touch
    mode: 0644

- name: java | Add deb to webupd8team source list
  lineinfile:
    path: /etc/apt/sources.list.d/webupd8team-java.list
    line: 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'

- name: java | Add deb src to webupd8team source list
  lineinfile:
    path: /etc/apt/sources.list.d/webupd8team-java.list
    line: 'deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'

- name: java | Get relevant key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EEA14886

- name: java | Install java
  apt:
    pkg: "{{ apt_java_package }}"
    update_cache: yes
