version: 2
jobs:
  test:
    docker:
      - image: cpdbdev/cpdbv2_backend:0.1.0
      - image: cpdbdev/postgis:9.4-alpine
        command: postgres
      - image: elasticsearch:5-alpine
      - image: selenium/standalone-chrome:3.11
    environment:
      - DJANGO_SETTINGS_MODULE: config.settings.circleci
      - DATABASE_URL: postgis://cpdb:password@127.0.0.1:5432/cpdb
    steps:
      - checkout
      - run: pip install --user -r requirements/test.txt
      - run: flake8
      - run: coverage run cpdb/manage.py test --noinput --nologcapture
      - run: coverage combine
      - run: coverage report --omit="/home/ubuntu/virtualenvs/*,common/json_serializer.py"
      - run: coveralls
      - store_artifacts:
          path: /home/deploy/project/cpdb/test_visual_token_media

  deploy:
    docker:
      - image: cpdbdev/cpdbv2_backend:0.1.0
    environment:
      - NODE_ENV: development
    steps:
      - checkout
      - run: bin/circleci_deploy_staging

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: staging
