version: 2
jobs:
  test:
    docker:
      - image: cpdbdev/cpdbv2_backend:0.1.0
      - image: cpdbdev/postgis:9.6-alpine
        command: postgres
      - image: elasticsearch:5-alpine
      - image: selenium/standalone-chrome:3.11
    environment:
      - DJANGO_SETTINGS_MODULE: config.settings.circleci
      - DB_HOST: localhost
      - DB_USER: cpdb
      - DB_PASSWORD: password
      - DB_NAME: cpdb
    steps:
      - checkout
      - run: pip install --user -r requirements/test.txt
      - run: flake8
      - run: coverage run cpdb/manage.py test --noinput --nologcapture
      - run: coverage combine
      - run: coverage report --omit="/home/ubuntu/virtualenvs/*"
      - run: coveralls
      - store_artifacts:
          path: /home/deploy/project/cpdb/test_visual_token_media

  deploy:
    docker:
      - image: cpdbdev/cpdbv2_backend:0.1.0
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      - run:
          command: bin/circleci_deploy_staging
          no_output_timeout: 60m

  build_cpdpbot:
    machine: true
    steps:
      - checkout
      - run:
          name: Build cpdpbot image
          command: docker build -t cpdbdev/cpdpbot:$(cat docker/cpdpbot/VERSION) docker/cpdpbot
      - run:
          name: Test cpdpbot image
          command: docker run --rm cpdbdev/cpdpbot:$(cat docker/cpdpbot/VERSION) python -m cpdpbot.test
      - run:
          name: Push cpdpbot image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push cpdbdev/cpdpbot:$(cat docker/cpdpbot/VERSION)

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: staging

  test_deploy_cpdpbot:
    jobs:
      - build_cpdpbot
