---
- name: elastic-install | Install python-software-properties
  apt:
    pkg=python-software-properties
    state=present
    update_cache=yes

- name: elastic-install | Install dependencies
  apt:
    pkg={{ item }}
    state=present
  with_items: "{{ elasticsearch_apt_dependencies }}"

- name: elastic-install | Configuring elastic group
  group:
    name={{ elasticsearch_group }}

- name: elastic-install | Configuring elastic user
  user:
    name={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    createhome=no

- name: elastic-install | Ensure temp elasticsearch directories exists
  file:
    path="{{ elasticsearch_work_dir }}"
    state=directory
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    recurse=yes

- name: elastic-install | Ensure data directories exists
  file:
    path="{{ elasticsearch_data_dir }}"
    state=directory
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    recurse=yes

- name: elastic-install | Check if we have elastic with same version installed
  stat:
    path="/usr/share/elasticsearch/lib/elasticsearch-{{ elasticsearch_version }}.jar"
  register: installed_version

- name: elastic-install | Download Elasticsearch deb
  get_url:
    url={{ elasticsearch_download_url }}/elasticsearch-{{ elasticsearch_version }}.deb
    dest=/tmp/elasticsearch-{{ elasticsearch_version }}.deb
    mode=0440
  when: not installed_version.stat.exists

#shell: dpkg --remove elasticsearch
- name: elastic-install | Uninstalling previous version if applicable
  apt:
     name="elasticsearch"
     state="absent"
  when: not installed_version.stat.exists

- name: elastic-install | Remove elasticsearch directory
  file:
    path="{{ elasticsearch_home_dir }}"
    state=absent
  when: not installed_version.stat.exists

- name: elastic-install | Install Elasticsearch deb
  shell: dpkg -i -E --force-confnew /tmp/elasticsearch-{{ elasticsearch_version }}.deb
  when: not installed_version.stat.exists
  notify: Restart Elasticsearch

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes


