---

elasticsearch_user: elasticsearch
elasticsearch_group: elasticsearch
elasticsearch_download_url: https://download.elasticsearch.org/elasticsearch/elasticsearch
elasticsearch_version: 2.3.5
elasticsearch_apt_java_package: oracle-java7-installer
elasticsearch_apt_dependencies:
  - htop
  - ntp
  - unzip
elasticsearch_home_dir: /usr/share/elasticsearch
elasticsearch_work_dir: /tmp/elasticsearch
