apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
spec:
  template:
    spec:
      containers:
      - name: gunicorn
        image: cpdbdev/backend:${BACKEND_IMAGE_TAG}
        command: ["${COMMAND}", "${ARGS}"]
        env:
          - name: AWS_ACCESS_KEY_ID
            value: "${AWS_ACCESS_KEY_ID}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "${AWS_SECRET_ACCESS_KEY}"
          - name: AWS_DEFAULT_REGION
            value: "${AWS_DEFAULT_REGION}"
      restartPolicy: Never
  backoffLimit: 4
