apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gunicorn
  labels:
    app: gunicorn
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gunicorn
    spec:
      containers:
      - name: gunicorn
        image: cpdbdev/cpdbv2_backend:{{BACKEND_IMAGE_TAG}}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gunicorn
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: gunicorn
