apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: cpdbdev/postgres:{{POSTGRES_IMAGE_TAG}}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 2
            memory: 4Gi
        env:
        - name: POSTGRES_APP_DB
          value: "{{POSTGRES_APP_DB}}"
        - name: POSTGRES_APP_USER
          value: "{{POSTGRES_APP_USER}}"
        - name: POSTGRES_APP_PASSWORD
          value: "{{POSTGRES_APP_PASSWORD}}"
        - name: POSTGRES_NUMERACY_PASSWORD
          value: "{{POSTGRES_NUMERACY_PASSWORD}}"
        - name: POSTGRES_NOTEBOOK_PASSWORD
          value: "{{POSTGRES_NOTEBOOK_PASSWORD}}"
        - name: POSTGRES_CIVIS_PASSWORD
          value: "{{POSTGRES_CIVIS_PASSWORD}}"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: tls-secrets
          mountPath: "/tls-secrets"
          readOnly: true
        - mountPath: "/var/lib/postgresql/data"
          name: pg-data-disk
      volumes:
      - name: tls-secrets
        secret:
          secretName: tls-secret
      - name: pg-data-disk
        persistentVolumeClaim:
          claimName: pg-data-disk
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer
  ports:
  - port: 5432
  selector:
    app: postgres
