---

- name: Install cairo
  apt:
    name: libcairo2-dev

- name: Add mc3man repository
  apt_repository:
    repo: ppa:mc3man/trusty-media

- name: Upgrade apt dist
  apt:
    upgrade: dist

- name: Install ffmpeg
  apt:
    name: ffmpeg
    update_cache: yes
