---

- name: Restart nginx
  service: name=nginx state=restarted enabled=yes


- name: Supervisor restart web process
  supervisorctl: name={{ application_name }} state=restarted

- name: Supervisor restart twitterbot
  supervisorctl: name=twitterbot state=restarted
  when: run_twitterbot
