---

- name: Restart nginx
  service: name=nginx state=restarted enabled=yes

- name: Restart Supervisor
  supervisorctl: name={{ item }} state=restarted
  with_items:
    - "{{ application_name }}"
    - twitterbot
