---
- name: Update rsyslog to newest version
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - rsyslog
    - rsyslog-gnutls

- name: Download papertrail CA file
  get_url:
    url: https://papertrailapp.com/tools/papertrail-bundle.pem
    dest: /etc/papertrail-bundle.pem
    mode: 0644

- name: Add papertrail config to rsyslog
  template:
    src: papertrail.conf.j2
    dest: /etc/rsyslog.d/95-papertrail.conf
    mode: 0644
  notify: restart rsyslog

- name: Install remote-syslog2
  apt:
    deb: https://github.com/papertrail/remote_syslog2/releases/download/v0.20/remote-syslog2_0.20_amd64.deb

- name: Create the remote_syslog init script
  template:
    src: remote_syslog_init.j2
    dest: /etc/supervisor/conf.d/remote_syslog.conf
    backup: yes

- name: Make sure remote_syslog init script is read
  supervisorctl:
    name: remote_syslog
    state: present

- name: Add remote syslog config
  template:
    src: log_files.yml.j2
    dest: /etc/log_files.yml
    mode: 0644
  notify: restart remote_syslog
