---

- name: create newrelic config file
  shell: source {{ virtualenv_path }}/bin/activate && newrelic-admin generate-config {{ newrelic_license }} newrelic.ini
    chdir={{ project_root_path }}
  args:
    executable: /bin/bash
  notify: restart application

- name: config newrelic apt repository
  become: yes
  become_user: root
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present

- name: trust newrelic gpg key
  become: yes
  become_user: root
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present

- name: install newrelic-sysmond
  become: yes
  become_user: root
  apt: name=newrelic-sysmond update_cache=yes state=installed

- name: config newrelic license key
  become: yes
  become_user: root
  command: nrsysmond-config --set license_key={{ newrelic_license }}

- name: ensure newrelic-sysmond started
  become: yes
  become_user: root
  command: /etc/init.d/newrelic-sysmond start
