---
- name: Install specific python version
  script: install-python.sh {{ python_version }}
  become: yes
  become_user: deploy

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: Create the virtualenv
  script: create-env.sh {{ pyenv_root }}/versions/{{ python_version }}/bin/python {{ application_name }}
  become: yes
  become_user: deploy

- name: Ensure gunicorn is installed
  pip: virtualenv={{ virtualenv_path }} name=gunicorn
  become: yes
  become_user: deploy

- name: Create the Gunicorn script file
  template: src=gunicorn_start.j2
            dest={{ virtualenv_path }}/bin/gunicorn_start
            owner=deploy
            group=deploy
            mode=0755
            backup=yes
  tags: deploy

- name: Create the application log folder
  file: path={{ application_log_dir }}
        owner=deploy
        group=deploy
        mode=0774
        state=directory

- name: Create the application log file
  command: touch {{ application_log_file }}
           creates={{ application_log_file }}

- name: Set permission to the application log file
  file: path={{ application_log_file }}
        owner=deploy
        group=deploy
        mode=0664
        state=file

- name: Create the maintenance page
  template: src=maintenance_off.html
            dest={{ virtualenv_path }}/maintenance_off.html
            mode=0664
