---

- name: Make sure database is backup daily
  cron: name="backup database"
    special_time=daily
    job="/bin/bash -c 'source {{ project_root_path }}/bin/activate_env.sh && {{ project_root_path }}/cpdb/manage.py backup_current_database'"
  when: backup_database_daily
