---

- name: create newrelic config file
  template: src='newrelic.j2' dest={{ project_root_path }}/newrelic.ini
  notify: restart application

- name: create Twitterbot newrelic config file
  template: src='twitterbot_newrelic.j2' dest={{ project_root_path }}/twitterbot_newrelic.ini
  notify: restart application

- name: config newrelic apt repository
  become: yes
  become_user: root
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present

- name: trust newrelic gpg key
  become: yes
  become_user: root
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present

- name: install newrelic-sysmond
  become: yes
  become_user: root
  apt: name=newrelic-sysmond update_cache=yes state=installed

- name: config newrelic license key
  become: yes
  become_user: root
  command: nrsysmond-config --set license_key={{ newrelic_license }}

- name: ensure newrelic-sysmond started
  become: yes
  become_user: root
  command: /etc/init.d/newrelic-sysmond start
