---

- name: Create the Supervisor config file
  template: src=supervisor_config.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}.conf
            backup=yes

- name: Re-read the Supervisor config files
  supervisorctl: name={{ item }} state=present
  with_items:
    - "{{ application_name }}"
    - twitterbot

- name: Restart Supervisor
  supervisorctl: name={{ item }} state=restarted
  with_items:
    - "{{ application_name }}"
    - twitterbot
