---

- name: Setup the Git repo
  git: repo={{ git_repo }}
       version="{{ git_branch }}"
       dest={{ project_root_path }}
       accept_hostkey=yes
       key_file={{ github_ssh_key }}
  when: setup_git_repo is defined and setup_git_repo
  tags: git
  become: yes
  become_user: "{{ deploy_user }}"

- name: Remove all .pyc files
  command: find . -name \*.pyc -delete
  args:
    chdir: "{{ project_root_path }}"
  become: yes
  become_user: "{{ deploy_user }}"

- name: Create static folder if it is not there
  file: path={{ staticfiles_dir }}
        owner={{ deploy_user }}
        group={{ deploy_group }}
        state=directory

- name: Setup .env file
  template:
    src: env.j2
    dest: "{{ project_root_path }}/.env"
    force: "{{ force_rewrite_env_file }}"
  become: yes
  become_user: "{{ deploy_user }}"

- name: Create pam_environment file
  template:
    src: env.j2
    dest: /home/{{ deploy_user }}/.pam_environment
    owner: "{{ deploy_user }}"
  when: create_pam_environment
  become: yes
  become_user: "{{ deploy_user }}"
