---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant-secrets.yml
    - env_vars/vagrant.yml
  roles:
    - base
    - { role: azavea.postgresql }
    - { role: gpstathis.elasticsearch, es_instance_name: "vagrant",
        es_config: { 'network.host': "0.0.0.0", 'http.port': 9200 },
        ansible_become: yes,
        ansible_become_user: root,
        tags: elastic
      }
    - db
    - web
