---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: yes
  become_user: root
  remote_user: "{{ansible_remote_user}}"
  vars:
    - ansible_remote_user: vagrant
    - create_pam_environment: no
    - update_apt_cache: yes
    - postgresql_version: "9.4"
    - postgresql_package_version: "9.4.*-1.pgdg14.04+1"
    - requirements_file: "{{ project_root_path }}/requirements/local.txt"
    - elasticsearch_network_host: 0.0.0.0
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant-secrets.yml
    - env_vars/vagrant.yml
  roles:
    - base
    - { role: azavea.postgresql }
    - { role: java, tags: "elasticsearch" }
    - { role: elasticsearch, tags: "elasticsearch" }
    - db
    - { role: ssh_user, tags: "ssh_user" }
    - web
