---

- name: restart application
  supervisorctl: name={{ application_name }} state=restarted

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart remote_syslog
  supervisorctl:
    name: remote_syslog
    state: restarted
